laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('imoveis', 'ImoveisController@index')->name('imoveis');
    Route::get('imoveis/{codigo_imovel}', 'ImoveisController@show')->name('imoveis.show');
    Route::get('anuncie-seu-imovel', 'AnuncieController@index')->name('anuncie');
    Route::post('anuncie-seu-imovel', 'AnuncieController@post')->name('anuncie.post');
    Route::get('espaco-talenco/{categoria_slug?}', 'BlogController@index')->name('blog');
    Route::get('espaco-talenco/{categoria_slug}/{post_slug}', 'BlogController@show')->name('blog.show');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('a-talenco', 'EmpresaController@index')->name('empresa');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe.post');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Retorna JSON com os 3 últimos posts do blog
    Route::get('posts-json', function() {
        return \App\Models\Post::with('categoria')->publicados()->ordenados()->take(3)->get();
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');
		Route::resource('blog/categorias', 'BlogCategoriasController', ['parameters' => ['categorias' => 'categorias_blog']]);
		Route::resource('blog', 'BlogController');

        Route::group(['middleware' => 'acessoCompleto'], function() {
            /* GENERATED ROUTES */
		Route::resource('trabalhe-conosco', 'TrabalheConoscoController', ['only' => ['index', 'update']]);
            Route::resource('destaques', 'DestaquesController', ['only' => ['index', 'update']]);
    		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
    		Route::resource('banners', 'BannersController');
            Route::get('curriculos/{curriculos}/toggle', ['as' => 'painel.curriculos.toggle', 'uses' => 'CurriculosController@toggle']);
            Route::resource('curriculos', 'CurriculosController');
            Route::get('imoveis/{imoveis}/toggle', ['as' => 'painel.imoveis.toggle', 'uses' => 'ImoveisController@toggle']);
            Route::resource('imoveis', 'ImoveisController');
    		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

            Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
            Route::resource('contato/recebidos', 'ContatosRecebidosController');
            Route::resource('contato', 'ContatoController');
            Route::resource('usuarios', 'UsuariosController');
            Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
            Route::resource('newsletter', 'NewsletterController');

            Route::post('ckeditor-upload', 'PainelController@imageUpload');
            Route::post('order', 'PainelController@order');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

            Route::get('generator', 'GeneratorController@index')->name('generator.index');
            Route::post('generator', 'GeneratorController@submit')->name('generator.submit');

            Route::get('atualizar-imoveis', function() {
                Cache::forget('imoveis');
                Tools::fetchImoveis();
                return redirect()->route('painel')->with('success', 'Imóveis atualizados com sucesso.');
            })->name('atualizar-imoveis');
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BlogCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogCategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\PostCategoria;

class BlogCategoriasController extends Controller
{
    public function index()
    {
        $categorias = PostCategoria::ordenados()->get();

        return view('painel.blog.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.blog.categorias.create');
    }

    public function store(BlogCategoriasRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = PostCategoria::upload_capa();

            PostCategoria::create($input);
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(PostCategoria $categoria)
    {
        return view('painel.blog.categorias.edit', compact('categoria'));
    }

    public function update(BlogCategoriasRequest $request, PostCategoria $categoria)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = PostCategoria::upload_capa();

            $categoria->update($input);
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(PostCategoria $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogRequest;
use App\Http\Controllers\Controller;

use App\Models\Post;
use App\Models\PostCategoria;

class BlogController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = PostCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (PostCategoria::find($filtro)) {
            $registros = Post::where('blog_categoria_id', $filtro)->orderBy('id', 'DESC')->get();
        } else {
            $registros = Post::ordenados()->get();
        }

        return view('painel.blog.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.blog.create', compact('categorias'));
    }

    public function store(BlogRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Post::upload_capa();

            $input['slug'] = str_slug($input['slug']);

            if (count(Post::where('slug', $input['slug'])->get())) {
                throw new \Exception('O slug inserido já existe.', 1);
            }

            Post::create($input);

            return redirect()->route('painel.blog.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()])->withInput();

        }
    }

    public function edit(Post $registro)
    {
        $categorias = $this->categorias;

        return view('painel.blog.edit', compact('registro', 'categorias'));
    }

    public function update(BlogRequest $request, Post $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Post::upload_capa();

            $input['slug'] = str_slug($input['slug']);

            if (count(Post::where('id', '!=', $registro->id)->where('slug', $input['slug'])->get())) {
                throw new \Exception('O slug inserido já existe.', 1);
            }

            $registro->update($input);

            return redirect()->route('painel.blog.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()])->withInput();

        }
    }

    public function destroy(Post $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.blog.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/CurriculosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\CurriculoRecebido;

class CurriculosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = CurriculoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.curriculos.index', compact('contatosrecebidos'));
    }

    public function show(CurriculoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.curriculos.show', compact('contato'));
    }

    public function destroy(CurriculoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.curriculos.index')->with('success', 'Currículo excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir currículo: '.$e->getMessage()]);

        }
    }

    public function toggle(CurriculoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.curriculos.index')->with('success', 'Currículo alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar currículo: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DestaquesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DestaquesRequest;
use App\Http\Controllers\Controller;

use App\Models\Destaques;

class DestaquesController extends Controller
{
    public function index()
    {
        $registro = Destaques::first();

        return view('painel.destaques.edit', compact('registro'));
    }

    public function update(DestaquesRequest $request, Destaques $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.destaques.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ $config->nome_do_site }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName()) || str_is('painel.configuracoes*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        @if(\Auth::user()->acesso == 1)
                        <li @if(str_is('painel.configuracoes*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(str_is('painel.usuarios*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ route('atualizar-imoveis') }}">Atualizar Imóveis</a>
                        </li>
                        <li class="divider"></li>
                        @endif
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
@if(\Auth::user()->acesso == 1)
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
    {{--<li @if(str_is('painel.destaques*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.destaques.index') }}">Destaques</a>
    </li>--}}
    <li @if(str_is('painel.empresa*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.empresa.index') }}">Empresa</a>
    </li>
    <li @if(str_is('painel.imoveis*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.imoveis.index') }}">
            Imóveis
            @if($imoveisNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $imoveisNaoLidos }}</span>
            @endif
        </a>
    </li>
@endif
    <li @if(str_is('painel.blog*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.blog.index') }}">Blog</a>
    </li>
@if(\Auth::user()->acesso == 1)
	<li @if(str_is('painel.trabalhe-conosco*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.trabalhe-conosco.index') }}">Trabalhe Conosco</a>
	</li>
    <li @if(str_is('painel.curriculos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.curriculos.index') }}">
            Currículos
            @if($curriculosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $curriculosNaoLidos }}</span>
            @endif
        </a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName()) || str_is('painel.newsletter*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
            <li class="divider"></li>
            <li @if(str_is('painel.newsletter*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
            </li>
        </ul>
    </li>
@endif
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ $config->nome_do_site }} - Painel Administrativo</title>

    {!! Tools::loadCss('vendor/bootswatch-dist/css/bootstrap.min.css') !!}
    {!! Tools::loadCss('css/vendor.painel.css') !!}
    {!! Tools::loadCss('css/painel.css') !!}
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    {!! Tools::loadJquery() !!}
    {!! Tools::loadJs('vendor/ckeditor/ckeditor.js') !!}
    {!! Tools::loadJs('js/vendor.painel.js') !!}
    {!! Tools::loadJs('js/painel.js') !!}
</body>
</html>